services:
  server:
    build:
      context: server
      target: server
    container_name: server
    restart: unless-stopped
    ports:
      - ${BACK_PORT}:${BACK_PORT}
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./server:/app

  db:
    image: postgres:15
    container_name: area-db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql

  client_mobile:
    build:
      context: client_mobile
      target: client_mobile
    container_name: client_mobile
    volumes:
      - ./build:/app/build/

  client_web:
    build:
      context: client_web
      target: client_web
    container_name: client_web
    restart: unless-stopped
    ports:
      - ${FRONT_PORT}:${FRONT_PORT}
    environment:
      NEXT_PUBLIC_BACK_URL: ${NEXT_PUBLIC_BACK_URL}
    depends_on:
      - server
      - client_mobile
    volumes:
      - ./client_web:/app
      - ./build:/app/build/

volumes:
  db-data:
