services:
  server:
    build:
      context: .
      target: server
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/app/src
  db:
    image: postgres:15
    restart: unless-stopped
    container_name: area-db
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
