stages:
  - ✅ install
  - 🖌 format
  - 🛠 apk-build
  - 📦 update

variables:
  NODE_IMAGE: node:18.12.0-alpine
  DOCKER_IMAGE: docker:20.10.19
  ALPINE_IMAGE: alpine:3.14.2
  NPM_GLOBAL_CACHE: /cache/.npm_global_cache
  FF_USE_FASTZIP: 'true'
  ARTIFACT_COMPRESSION_LEVEL: 'fast'
  CACHE_COMPRESSION_LEVEL: 'fast'
  GIT_DEPTH: 1

.node_modules_cache_var:
  - &node_modules_cache
    key:
      files:
        - package-lock.json
    paths:
      - node_modules
    policy: pull

install:
  image: $NODE_IMAGE
  stage: ✅ install
  cache:
    - <<: *node_modules_cache
      policy: push
  script:
    - npm ci --cache $NPM_GLOBAL_CACHE
  except:
    - tags

lint:
  image: $NODE_IMAGE
  stage: 🖌 format
  cache:
    - *node_modules_cache
  script:
    - npm run lint
  except:
    - tags

# build:
#   image: docker
#   services:
#     - docker:dind
#   variables:
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ''
#     DOCKER_IMAGE: ''
#   stage: 🛠 apk-build
#   cache:
#     - *node_modules_cache
#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
#     - docker run --rm --privileged -v $PWD:/app -w /app $DOCKER_IMAGE sh -c "cd /app/android && ./gradlew init && ./gradlew assembleRelease"
#   except:
#     - tags

update:
  image: $ALPINE_IMAGE
  stage: 📦 update
  script:
    - apk add --no-cache git
    - git clone https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/EpitechPromo2025/$GITHUB_REPO_NAME.git /tmp/
    - mkdir -p /tmp/client_mobile
    - rm -rf /tmp/client_mobile/*
    - cp -af . /tmp/client_mobile
    - cd /tmp/
    - git config user.name "$GITLAB_USERNAME"
    - git config user.email "gitlab@ci.com"
    - git add -A
    - git commit -m "Update client_mobile"
    - git push https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/EpitechPromo2025/$GITHUB_REPO_NAME.git
  only:
    - main
